name: dhmcStats
main: me.botsko.dhmcstats.Dhmcstats
version: 0.3.1
softdepend: [PermissionsEx]
commands:
   played:
      description: Displays a player's play time on this server.
      usage: /played [player]
   playhist:
      description: Displays a player's play time for the past seven joins.
      usage: /playhist [player]
   player:
      description: Displays a player's stats.
      usage: /player [player]
   playerstats:
      description: Displays a few statistics of player counts.
      usage: /playerstats
   seen:
      description: Display join and last seen dates for a player.
      usage: /seen [player]
   rank:
      description: Displays rank information, mainly qualification for next rank.
      usage: /rank [player]
   ison:
      description: Checks if the user is online.
      usage: /ison [player]
   scores:
      description: Checks the newmod scores of a users
      usage: /scores [player]
   warn:
      description: File an official warning against a player
      usage: /warn [player] [reason]
   warnings:
      description: See warnings for a player
      usage: /warnings [player]
   z:
      description: Macro for text
      usage: /z [choice]
   dhmc:
      description: For admins
      usage: /dhmc (sanity)
   from:
      description: Tell us where you heard about us!
      usage: /from (how did you find out about dhmc?)